name: Auto-Fix Sentry Issue

on:
  issues:
    types: [opened]
  workflow_dispatch:

jobs:
  auto_fix:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'sentry')
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python (for AI fix script)
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install openai requests

      - name: Generate Fix
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ISSUE_BODY: ${{ github.event.issue.body }}
        run: python .github/scripts/auto_fix.py

      - name: Create a New Branch
        run: |
          BRANCH_NAME="auto-fix-${{ github.event.issue.number }}"
          git checkout -b $BRANCH_NAME
          git add .
          git commit -m "Auto-fix for Issue #${{ github.event.issue.number }}"
          git push origin $BRANCH_NAME

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: "auto-fix-${{ github.event.issue.number }}"
          title: "Auto-Fix: Issue #${{ github.event.issue.number }}"
          body: "This PR includes an automated fix for issue #${{ github.event.issue.number }} detected by Sentry."
          labels: "auto-generated, needs-review"
